version: 2
jobs:
  build:
    working_directory: ~/89tech
    machine: true
    steps:
      - checkout
      - run:
          name: install hugo
          command: go get -v github.com/gohugoio/hugo
      - run:
          name: run hugo
          command: hugo
      - run:
          name: Print the Current Time
          command: date
      - save_cache:
          key: buildend-{{ epoch }}
          paths:
            - ~/89tech

  deploy:
    working_directory: ~/89tech
    machine: true
    steps:
      - restore_cache:
          keys:
            - buildend
      - run:
          name: install firebase
          command: npm install -g firebase-tools
      - run:
          name: firebase deploy
          command: firebase --project "$FIREBASE_PROJECTID" deploy --token "$FIREBASE_TOKEN"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
